### ISSUE TITLE
graphs are not updating properly

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustc-pr-tracking#7]
It looks like the graphs are no longer updating properly since a few days 
![pr-tracking](https://user-images.githubusercontent.com/476013/68856821-b3130d80-06e1-11ea-8716-2918af9859b8.jpg)

**Comment by Mark-Simulacrum** [comment]
cc @kennytm @pietroalbini -- I wasn't able to figure out what was wrong when I last looked at this, everything seemed to mostly work locally, aside from possibly the time when we run the cronjob being wrong

**Comment by Mark-Simulacrum** [comment]
I've tried to move us to GH actions, but for some reason when I click on "Enable GH actions" it tells me that it cannot currently enable GH actions. Maybe I'm doing something wrong? @pietroalbini -- do you know if we need to be in the rust-lang repository for GH actions to work?

**Comment by pietroalbini** [comment]
It *should* work on the nursery, dunno why it failed to enabled. It errored out for me as well, so I just migrated the repo to the rust-lang org.
