### ISSUE TITLE
graphs not updating

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustc-pr-tracking#9]
https://rust-lang.github.io/rustc-pr-tracking/
The latest update is from 2019-12-03, that's 24 days ago.

**Comment by Mark-Simulacrum** [comment]
The good news is that data is being collected. Unfortunately, GH pages doesn't seem to be building -- I see " Your site is having problems building: Page build failed. " in the settings which is pretty unhelpful.

**Comment by Mark-Simulacrum** [comment]
Using jekyll inside Docker locally also seems to work :/

**Comment by Mark-Simulacrum** [comment]
Ah, it seems that we cannot trigger GH pages builds via the GITHUB_TOKEN provided to GH Actions. (cc @pietroalbini, this is unexpected)

It seems that it's possible to manually trigger a build without pushing a commit -- https://developer.github.com/v3/repos/pages/#request-a-page-build -- but I'm presuming that can't be done from GH actions. I'm not sure what the best path forward here is, let's see if @pietroalbini has thoughts -- for now, I'll run a crontab locally hitting the request a page build from time to time I guess.

**Comment by pietroalbini** [comment]
> Ah, it seems that we cannot trigger GH pages builds via the GITHUB_TOKEN provided to GH Actions.

GitHub knows about this. Have you tried using deploy keys?

**Comment by Mark-Simulacrum** [comment]
Hm, no. That's a good idea - I'll try that out.

**Comment by matthiaskrgr** [comment]
The issue has been fixed long ago, closing :)
